Entrenant el model...
/home/grau/myenv/lib/python3.12/site-packages/numpy/ma/core.py:2881: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,
confusion matrix:  [[145   4]
 [  3 168]]
accuracy:  0.978125
Params:  {'bootstrap': False, 'criterion': 'gini', 'max_depth': 20, 'n_estimators': 300}
Overfitting =  1.0
Resultats test =  0.978125
Visualitzant les m√®triques...
